spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ssafy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  profiles:
    active: jwt, oauth

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ??? ?? 2.x, hibernate5

project:
  properties:
    firebase-create-scoped: "https://developers.google.com/identity/protocols/oauth2/scopes" #"https://www.googleapis.com/auth/firebase.messaging"
    firebase-topic: "diet_record_notification"